### ISSUE TITLE
MonoDevelop is corrupted after installation

### ISSUE THREAD

**Issue by James-Ko** [dnschneid/crouton#1260]
When I open up MonoDevelop in 12.04 LTS, I get a corrupt screen and a huge black box whenever I try to open a file. I have a NVIDIA Tegra K1 processor which I think may be the root of the problem because it's armhf; what can I do?

**Comment by James-Ko** [comment]
When I ran `sudo sh ~/Downloads/crouton -r wheezy -t kde` and started crouton I got a ton of errors in crosh about audio (although it still ran) and a message about broken packages when I tried to install MonoDevelop (this was straight out of the box). So I decided to dig deeper into the problem in Unity.

When I tried starting Monodevelop from the terminal (`monodevelop`) I got an error about `Gtk-Message: Failed to load module "unity-gtk-module"`, followed by a bunch of other errors:

    Script started on Sat 03 Jan 2015 06:13:31 PM EST
    ]0;(precise)james@localhost: ~(precise)james@localhost:~$ monodevelop
    ERROR [0001-00-735601 18:14:01Z]: Gtk-Message: Failed to load module "unity-gtk-module"
    Stack trace: 
       at MonoDevelop.Ide.IdeStartup.Run(MonoDevelop.Ide.MonoDevelopOptions options)
       at MonoDevelop.Ide.IdeStartup.Main(System.String[] args)
       at MonoDevelop.Startup.MonoDevelopMain.Main(System.String[] args)
    System.DivideByZeroException: Division by zero
      at System.DateTimeUtils.ToString (DateTime dt, Nullable`1 utc_offset, System.String format,     System.Globalization.DateTimeFormatInfo dfi) [0x00000] in <filename unknown>:0 
      at System.DateTimeUtils.ToString (DateTime dt, System.String format,     System.Globalization.DateTimeFormatInfo dfi) [0x00000] in <filename unknown>:0 
      at System.DateTime.ToString (System.String format, IFormatProvider provider) [0x00000] in     <filename unknown>:0 
      at System.Xml.XmlConvert.ToString (DateTime value, XmlDateTimeSerializationMode mode)     [0x00000] in <filename unknown>:0 
      at Mono.Addins.Setup.AddinSystemConfigurationWriter.WriteObject_RepositoryRecord     (Mono.Addins.Setup.RepositoryRecord ob, System.String element, System.String namesp, Boolean     isNullable, Boolean needType, Boolean writeWrappingElem) [0x00000] in <filename unknown>:0 
      at Mono.Addins.Setup.AddinSystemConfigurationWriter.WriteObject_AddinSystemConfiguration     (Mono.Addins.Setup.AddinSystemConfiguration ob, System.String element, System.String namesp,     Boolean isNullable, Boolean needType, Boolean writeWrappingElem) [0x00000] in <filename     unknown>:0 
      at Mono.Addins.Setup.AddinSystemConfigurationWriter.WriteRoot_AddinSystemConfiguration     (System.Object o) [0x00000] in <filename unknown>:0 
      at Mono.Addins.Setup.AddinSystemConfigurationSerializer.Serialize (System.Object o,     System.Xml.Serialization.XmlSerializationWriter writer) [0x00000] in <filename unknown>:0 
      at System.Xml.Serialization.XmlSerializer.Serialize (System.Xml.XmlWriter writer, System.Object     o, System.Xml.Serialization.XmlSerializerNamespaces namespaces) [0x00000] in <filename     unknown>:0 
    WARNING [0001-00-735601 18:14:02Z]: Inotify watch limit is too low (8192).
    MonoDevelop will switch to managed file watching.
    See http://monodevelop.com/Inotify_Watches_Limit for more info.
    FATAL ERROR [0001-00-735601 18:14:02Z]: 
    System.NullReferenceException: Object reference not set to an instance of an object
      at MonoDevelop.Ide.IdePreferences.get_DefaultTargetRuntime () [0x00000] in <filename     unknown>:0 
      at MonoDevelop.Ide.RootWorkspace.set_UseDefaultRuntime (Boolean value) [0x00000] in     <filename unknown>:0 
      at MonoDevelop.Ide.RootWorkspace..ctor () [0x00000] in <filename unknown>:0 
      at MonoDevelop.Ide.IdeApp.Initialize (IProgressMonitor monitor) [0x00000] in <filename     unknown>:0 
      at MonoDevelop.Ide.IdeStartup.Run (MonoDevelop.Ide.MonoDevelopOptions options) [0x00000]     in <filename unknown>:0 
    ]0;(precise)james@localhost: ~(precise)james@localhost:~$ 

`strace monodevelop` results in this:

    ]0;(precise)james@localhost: ~(precise)james@localhost:~$ strace monodevelop
    execve("/usr/bin/monodevelop", ["monodevelop"], [/* 37 vars */]) = 0
    brk(0)                                  = 0x1fe5000
    uname({sys="Linux", node="localhost", ...}) = 0
    access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
    mmap2(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) =     0xb6fd8000
    access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
    open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
    fstat64(3, {st_mode=S_IFREG|0644, st_size=53763, ...}) = 0
    mmap2(NULL, 53763, PROT_READ, MAP_PRIVATE, 3, 0) = 0xb6faf000
    close(3)                                = 0
    access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
    open("/lib/arm-linux-gnueabihf/libtinfo.so.5", O_RDONLY|O_CLOEXEC) = 3
    .
    .
    .
    rt_sigaction(SIGINT, {0x37f25, [], 0x4000000 /* SA_??? */}, {SIG_DFL, [], 0x4000000 /* SA_??? */},     8) = 0
    wait4(-1, ERROR [0001-00-735601 18:15:33Z]: Gtk-Message: Failed to load module "unity-gtk-    module"
    Stack trace: 
       at MonoDevelop.Ide.IdeStartup.Run(MonoDevelop.Ide.MonoDevelopOptions options)
       at MonoDevelop.Ide.IdeStartup.Main(System.String[] args)
       at MonoDevelop.Startup.MonoDevelopMain.Main(System.String[] args)
    System.DivideByZeroException: Division by zero
      at System.DateTimeUtils.ToString (DateTime dt, Nullable`1 utc_offset, System.String format,     System.Globalization.DateTimeFormatInfo dfi) [0x00000] in <filename unknown>:0 
      at System.DateTimeUtils.ToString (DateTime dt, System.String format,     System.Globalization.DateTimeFormatInfo dfi) [0x00000] in <filename unknown>:0 
      at System.DateTime.ToString (System.String format, IFormatProvider provider) [0x00000] in     <filename unknown>:0 
      at System.Xml.XmlConvert.ToString (DateTime value, XmlDateTimeSerializationMode mode)     [0x00000] in <filename unknown>:0 
      at Mono.Addins.Setup.AddinSystemConfigurationWriter.WriteObject_RepositoryRecord     (Mono.Addins.Setup.RepositoryRecord ob, System.String element, System.String namesp, Boolean     isNullable, Boolean needType, Boolean writeWrappingElem) [0x00000] in <filename unknown>:0 
      at Mono.Addins.Setup.AddinSystemConfigurationWriter.WriteObject_AddinSystemConfiguration     (Mono.Addins.Setup.AddinSystemConfiguration ob, System.String element, System.String namesp,     Boolean isNullable, Boolean needType, Boolean writeWrappingElem) [0x00000] in <filename     unknown>:0 
      at Mono.Addins.Setup.AddinSystemConfigurationWriter.WriteRoot_AddinSystemConfiguration     (System.Object o) [0x00000] in <filename unknown>:0 
      at Mono.Addins.Setup.AddinSystemConfigurationSerializer.Serialize (System.Object o,     System.Xml.Serialization.XmlSerializationWriter writer) [0x00000] in <filename unknown>:0 
      at System.Xml.Serialization.XmlSerializer.Serialize (System.Xml.XmlWriter writer, System.Object     o, System.Xml.Serialization.XmlSerializerNamespaces namespaces) [0x00000] in <filename     unknown>:0 
    WARNING [0001-00-735601 18:15:33Z]: Inotify watch limit is too low (8192).
    MonoDevelop will switch to managed file watching.
    See http://monodevelop.com/Inotify_Watches_Limit for more info.
    FATAL ERROR [0001-00-735601 18:15:34Z]: 
    System.NullReferenceException: Object reference not set to an instance of an object
      at MonoDevelop.Ide.IdePreferences.get_DefaultTargetRuntime () [0x00000] in <filename unknown>:0 
      at MonoDevelop.Ide.RootWorkspace.set_UseDefaultRuntime (Boolean value) [0x00000] in     <filename unknown>:0 
      at MonoDevelop.Ide.RootWorkspace..ctor () [0x00000] in <filename unknown>:0 
      at MonoDevelop.Ide.IdeApp.Initialize (IProgressMonitor monitor) [0x00000] in <filename     unknown>:0 
      at MonoDevelop.Ide.IdeStartup.Run (MonoDevelop.Ide.MonoDevelopOptions options) [0x00000]     in <filename unknown>:0 
    [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 3888
    wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 1}], 0, NULL) = 3887
    .
    .
    .

I have gotten errors about this `unity-gtk-module` before when starting GUI applications from the command line (gedit, for example), but they worked perfectly fine. I looked in Synaptic, online, and on disk (using find -name) but couldn't find anything close to the name.
