### ISSUE TITLE
I am not able to print the report in odoo 

### ISSUE THREAD

**Issue by adminusr** [dnschneid/crouton#1785]
Odoo Server Error
Traceback (most recent call last):
  File "D:\collegsol\addons\report\controllers\main.py", line 121, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "D:\collegsol\openerp\http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "D:\collegsol\addons\report\controllers\main.py", line 65, in report_routes
    pdf = report_obj.get_pdf(cr, uid, docids, reportname, data=options_data, context=context)
  File "D:\collegsol\openerp\api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "D:\collegsol\addons\report\models\report.py", line 273, in get_pdf
    paperformat, specific_paperformat_args, save_in_attachment
  File "D:\collegsol\openerp\api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "D:\collegsol\addons\report\models\report.py", line 430, in _run_wkhtmltopdf
    head_file.write(headers[index])
IndexError: list index out of range

**Comment by dnschneid** [comment]
Kinda surprised nobody referred you to #262 yet.
