### ISSUE TITLE
feature request - URL handler

### ISSUE THREAD

**Issue by tedm** [dnschneid/crouton#186]
could be a subset of clipboard sync (see #144) between chroot and chromeos, but request is to be able to copy a URL from a chroot, and paste it (or toss it) to an optimized chromeos window. Ideally with hot keys, but a click or two would be OK.

So while working in the chroot, browser activity will use the optimized browser, which is in Chroemos.

**Comment by EktaAwadhiya** [comment]
Hi ,



Problem in sending any request (like SPV, GPV ) from GenieAcs to CPE when CPE connects first time to ACS as "BOOTSTRAP" annd "BOOT" both ...




Following error comes in  :



"
2015-08-27T18:17:09.134Z - TypeError: Cannot read property 'ConnectionRequestURL' of undefined
    at /home/cpe/GenieACS/Nodejs/node-v0.12.6-linux-x64/lib/node_modules/genieacs/lib/api-functions.js:117:60
    at /home/cpe/GenieACS/Nodejs/node-v0.12.6-linux-x64/lib/node_modules/genieacs/node_modules/mongodb/lib/mongodb/collection/query.js:164:5
    at Cursor.nextObject (/home/cpe/GenieACS/Nodejs/node-v0.12.6-linux-x64/lib/node_modules/genieacs/node_modules/mongodb/lib/mongodb/cursor.js:773:5)
    at commandHandler (/home/cpe/GenieACS/Nodejs/node-v0.12.6-linux-x64/lib/node_modules/genieacs/node_modules/mongodb/lib/mongodb/cursor.js:741:14)
    at bound (domain.js:254:14)
    at runBound (domain.js:267:12)
    at /home/cpe/GenieACS/Nodejs/node-v0.12.6-linux-x64/lib/node_modules/genieacs/node_modules/mongodb/lib/mongodb/db.js:1905:9
    at bound (domain.js:254:14)
    at runBound (domain.js:267:12)
    at Server.Base._callHandler (/home/cpe/GenieACS/Nodejs/node-v0.12.6-linux-x64/lib/node_modules/genieacs/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)



"



Although we send "ConnectionRequestURL" in Inform message .

Like :


<ParameterValueStruct><Name>Device.ManagementServer.ParameterKey</Name><Value xsi:type="xsd:string">KKK</Value></ParameterValueStruct>

<ParameterValueStruct><Name>Device.ManagementServer.ConnectionRequestURL</Name><Value xsi:type="xsd:string">http://200.20.20.24:15285</Value></ParameterValueStruct></ParameterList>
