### ISSUE TITLE
Can't change ulimit

### ISSUE THREAD

**Issue by whitneyit** [dnschneid/crouton#2315]
I've installed trusty and I'm using it for a node development environment. I'm currently running into a an error with too many open files.

>Error: EMFILE: too many open files, open '/home/whitneyit/.babel.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1224:33)
    ...

After looking into this I've found numerous _solutions_  none of which seem to work :(

I've tried modifying the `ulimit` to no success.

```
$ ulimit -n 65536
-su: ulimit: open files: cannot modify limit: Operation not permitted
```

I've tried adding extra lines to `/etc/security/limits.conf`

```
* hard nofile 65536
* soft nofile 65536
root hard nofile 65536
root soft nofile 65536
whitneyit hard nofile 65536
whitneyit soft nofile 65536
```

Is there anything that we can do to work around this issue?

**Comment by whitneyit** [comment]
Just found a **REAL** solution to this on [askubuntu](http://askubuntu.com/questions/162229/how-do-i-increase-the-open-files-limit-for-a-non-root-user)

Adding `session required pam_limits.so` to `/etc/pam.d/common-session` does the trick
