### ISSUE TITLE
budgie desktop + ubuntu xenial === error

### ISSUE THREAD

**Issue by dwaindibbly** [dnschneid/crouton#2620]
```
alex@localhost ~> xinit


X.Org X Server 1.18.3
Release Date: 2016-04-04
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.13.0-86-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.10.18 #1 SMP Mon Jun 6 21:50:51 PDT 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=c96041ee-a407-964f-9008-caa1a227756e/PARTNROFF=1 hashtree=PARTUUID=c96041ee-a407-964f-9008-caa1a227756e/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=7cbb3b47efdfad7f54f169f792808195a691aa54 salt=01225692cd1092620138a232cbf3d0ac1a62a903d6120f4d88608bf1a5b97ebc" noinitrd vt.global_cursor_default=0 kern_guid=c96041ee-a407-964f-9008-caa1a227756e add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 18 May 2016  01:07:07AM
xorg-server 2:1.18.3-1ubuntu2.2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Fri Jun 10 19:13:13 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
Error executing command as another user: Not authorized

This incident has been reported.
crouton: version 1-20160518095657~master:fd37bb79
release: xenial
architecture: amd64
xmethod: xorg
targets: core,audio,cli-extra,xorg,x11,chrome-dev,gtk-extra
host: version 8350.21.0 (Official Build) dev-channel quawks 
kernel: Linux localhost 3.10.18 #1 SMP Mon Jun 6 21:50:51 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
No Chromium OS X server is available.
/usr/bin/gnome-session: 3: /usr/bin/gnome-session: gsettings: not found
gnome-session-binary[13667]: WARNING: Failed to connect to systemd: Error calling StartServiceByName for org.freedesktop.login1: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return code 1
gnome-session-binary[13667]: GLib-GObject-WARNING: invalid (NULL) pointer instance
gnome-session-binary[13667]: GLib-GObject-CRITICAL: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
gnome-session-binary[13667]: WARNING: Could not get session id for session. Check that logind is properly installed and pam_systemd is getting used at login.
Exited with an error
stdout: 
stderr: Traceback (most recent call last):
  File "/usr/share/session-migration/scripts/nautilus-unity-launcher-icon-rename.py", line 5, in <module>
    from gi.repository import Gio
ImportError: No module named gi.repository

Exited with an error
stdout: 
stderr: Traceback (most recent call last):
  File "/usr/share/session-migration/scripts/nautilus-unity-launcher-icon.py", line 5, in <module>
    from gi.repository import Gio
ImportError: No module named gi.repository

gnome-session-binary[13667]: WARNING: Could not parse desktop file budgie-desktop-nm-applet.desktop or it references a not found TryExec binary
/usr/lib/gnome-settings-daemon/gnome-settings-daemon-localeexec: 3: /usr/lib/gnome-settings-daemon/gnome-settings-daemon-localeexec: gsettings: not found
GNOME_KEYRING_CONTROL=/home/alex/.cache/keyring-4N5QIY
GNOME_KEYRING_CONTROL=/home/alex/.cache/keyring-4N5QIY
SSH_AUTH_SOCK=/home/alex/.cache/keyring-4N5QIY/ssh
GNOME_KEYRING_CONTROL=/home/alex/.cache/keyring-4N5QIY
SSH_AUTH_SOCK=/home/alex/.cache/keyring-4N5QIY/ssh

(gnome-settings-daemon:13703): power-plugin-WARNING **: Unable to start gsd_power manager: Error calling StartServiceByName for org.freedesktop.login1: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return code 1
error: XDG_RUNTIME_DIR not set in the environment.

(gnome-settings-daemon:13703): rfkill-plugin-WARNING **: Could not open RFKILL control device, please verify your installation

(gnome-settings-daemon:13703): media-keys-plugin-WARNING **: Failed to connect to systemd: Error calling StartServiceByName for org.freedesktop.login1: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return code 1

(gnome-settings-daemon:13703): GLib-GIO-CRITICAL **: g_dbus_proxy_call_internal: assertion 'G_IS_DBUS_PROXY (proxy)' failed

(gnome-settings-daemon:13703): PackageKit-WARNING **: failed to set proxy: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: SetProxy is not a valid method of interface org.freedesktop.PackageKit


(gnome-settings-daemon:13703): updates-plugin-WARNING **: failed to set proxies: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: SetProxy is not a valid method of interface org.freedesktop.PackageKit


(gnome-settings-daemon:13703): color-plugin-WARNING **: failed to obtain org.freedesktop.color-manager.create-profile auth

(budgie-wm:13801): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(budgie-wm:13801): GLib-GObject-CRITICAL **: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(budgie-wm:13801): mutter-WARNING **: Failed to load background 'file:///usr/share/backgrounds/gnome/adwaita-timed.xml': Error opening file: No such file or directory

(gnome-settings-daemon:13703): color-plugin-WARNING **: failed to create device: failed to obtain org.freedesktop.color-manager.create-device auth

** (budgie-wm:13801): WARNING **: wm.vala:173: Failed to get LoginD proxy: Error calling StartServiceByName for org.freedesktop.login1: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return code 1
** Message: manager.vala:395: Error loading typelibs: Typelib file for namespace 'Peas', version '1.0' not found

(budgie-panel:13816): GLib-GObject-CRITICAL **: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(budgie-panel:13816): GLib-GObject-CRITICAL **: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Unable to initiate PolKit: No session for pid 13837gnome-session-binary[13667]: WARNING: App 'budgie-polkit.desktop' exited with code 1
Unable to initiate PolKit: No session for pid 13843gnome-session-binary[13667]: WARNING: App 'budgie-polkit.desktop' exited with code 1
gnome-session-binary[13667]: WARNING: App 'budgie-polkit.desktop' respawning too quickly
gnome-session-binary[13667]: CRITICAL: We failed, but the fail whale is dead. Sorry....
Running exit commands...
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down Hangup
(II) Server terminated successfully (0). Closing log file.

alex@localhost ~> 
```
#### WHA?!?!

yeah, it opens taskbar and then dies
#### To Reproduce:

budgie desktop remix on ubuntu 16.04

**Comment by DennisLfromGA** [comment]
@dwaindibbly,

> alex@localhost ~> xinit
...
crouton: version 1-20160518095657~master:fd37bb79
release: xenial
architecture: amd64
xmethod: xorg
**targets: core,audio,cli-extra,xorg,x11,chrome-dev,gtk-extra**
host: version 8350.21.0 (Official Build) dev-channel quawks 
kernel: Linux localhost 3.10.18 #1 SMP Mon Jun 6 21:50:51 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
**No Chromium OS X server is available.**
...

You haven't installed *any* GUI desktop targets so there's nothing to launch.
Try `lxde`, or `lxde-desktop` my latest favorite, or choose one of the may others.

-**DennisL**

**Comment by tista500** [comment]
@dwaindibbly,

Do not launch `nm-applet` inside the crouton chroot. network-manage.service of systemd was not implemented/optimized in Crouton yet...

Regards.

**Comment by dwaindibbly** [comment]
@tista500 i'm not trying to

**Comment by dwaindibbly** [comment]
@tista500 and a few days later I find out I use your theme. clap, clap.

also, now how do I use budgie- things in lxsession ( and your theme. l like the theme )

**Comment by dbw44** [comment]
I'm having a similar problem - startx fails on Ubuntu 16.04 with message "Server connection lost", and xinit just gives a default window, cannot do UI configuration.

**Comment by tista500** [comment]
Greetings,

Hmm, please check this file out: `/usr/share/gnome-session/sessions/budgie-desktop.session`

And if you guys edited like this, budgie-desktop could run?

```diff
--- budgie-desktop.session	2016-09-01 01:04:50.698664486 +0900
+++ budgie-desktop.session.new	2016-09-01 01:04:30.995836236 +0900
@@ -38,5 +38,5 @@
 Name[sv_SE]=Budgie Skrivbord
 Name[tr]=Budgie Masaüstü
 Name[zh_CN]=Budgie 桌面
-RequiredComponents=budgie-wm;gnome-settings-daemon;budgie-panel;budgie-polkit;
+RequiredComponents=budgie-wm;gnome-settings-daemon;budgie-panel;
 DesktopName=Budgie Desktop
```

Regards.

**Comment by dbw44** [comment]
Hello,
         Thanks for your reply, but I am afraid it is mostly gibberish 
to me.  I don't have budgie, and I have no way to know what is in 
budgie-desktop.session.   My problem is that I upgraded my Ubuntu 
release to 16.04 from 14.04, and I may have deleted an essential file 
when I did some cleaning up, so that now "startx" fails with a message 
"server connection lost",  and I don't know why.  Anything that you can 
tell me to help would be appreciated.

Thanks,
David Westman

**Comment by Darling13** [comment]
Thank you Tista500, that fixed it for me.
