### ISSUE TITLE
npm install fails in crouton

### ISSUE THREAD

**Issue by usernamenumber** [dnschneid/crouton#2708]
```
name: precise
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/precise...
crouton: version 1-20160715134041~master:0dc76a22
release: precise
architecture: i386
targets: core,cli-extra
host: version 7520.67.0 (Official Build) stable-channel x86-zgb_he 
kernel: Linux localhost 3.8.11 #1 SMP Wed Jan 6 22:08:47 PST 2016 i686 i686 i386 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/precise as another instance is using it.
```
#### Please describe your issue:

Installing npm via `apt-get` works fine, but then when I attempt to run an `npm install` from a crouton chroot fails with a log like the following. I confirmed that all of the urls are all correct, and also tried adding `--no-bin-links` [this issue from another repo](https://github.com/google/coding-with-chrome/issues/20), but it made no difference. 

Here's what gets dumped to npm's debug log...

```
verbose cli [ 'node',
verbose cli   '/usr/bin/npm',
verbose cli   'install',
verbose cli   'bower',
verbose cli   'ember-cli',
verbose cli   '-g',
verbose cli   '--no-bin-links' ]
info using npm@1.1.4
info using node@v0.6.12
verbose config file /home/brad/.npmrc
verbose config file /usr/etc/npmrc
verbose config file /usr/share/npm/npmrc
silly exec /usr/bin/node "/usr/share/npm/bin/npm-get-uid-gid.js" "nobody" 1000
silly spawning [ '/usr/bin/node',
silly spawning   [ '/usr/share/npm/bin/npm-get-uid-gid.js', 'nobody', 1000 ],
silly spawning   null ]
silly output from getuid/gid {"uid":65534,"gid":1000}
silly output from getuid/gid 
verbose cache add [ 'bower', null ]
silly cache add: name, spec, args [ undefined, 'bower', [ 'bower', null ] ]
verbose parsed url { pathname: 'bower', path: 'bower', href: 'bower' }
verbose cache add [ 'ember-cli', null ]
silly cache add: name, spec, args [ undefined, 'ember-cli', [ 'ember-cli', null ] ]
verbose parsed url { pathname: 'ember-cli', path: 'ember-cli', href: 'ember-cli' }
verbose addNamed [ 'bower', '' ]
verbose addNamed [ null, '' ]
silly name, range, hasData [ 'bower', '', false ]
verbose addNamed [ 'ember-cli', '' ]
verbose addNamed [ null, '' ]
silly name, range, hasData [ 'ember-cli', '', false ]
verbose raw, before any munging bower
verbose url resolving [ 'https://registry.npmjs.org/', './bower' ]
verbose url resolved https://registry.npmjs.org/bower
http GET https://registry.npmjs.org/bower
verbose raw, before any munging ember-cli
verbose url resolving [ 'https://registry.npmjs.org/', './ember-cli' ]
verbose url resolved https://registry.npmjs.org/ember-cli
http GET https://registry.npmjs.org/ember-cli
ERR! Error: failed to fetch from registry: ember-cli
ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
ERR!     at Request.emit (events.js:88:20)
ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
ERR!     at ClientRequest.emit (events.js:67:17)
ERR!     at HTTPParser.onIncoming (http.js:1261:11)
ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
ERR! You may report this log at:
ERR!     <http://bugs.debian.org/npm>
ERR! or use
ERR!     reportbug --attach /home/brad/npm-debug.log npm
ERR! 
ERR! System Linux 3.8.11
ERR! command "node" "/usr/bin/npm" "install" "bower" "ember-cli" "-g" "--no-bin-links"
ERR! cwd /home/brad
ERR! node -v v0.6.12
ERR! npm -v 1.1.4
ERR! message failed to fetch from registry: ember-cli
```

The registry URL _does_ work, and it seems like the package downloads, but then something goes wrong after that. Same command works fine in a proper Linux install, so I don't think it's an issue with npm. Any ideas?

**Comment by drinkcat** [comment]
I'm really not sure, have you tried asking on some npm support forum?
