### ISSUE TITLE
Appium installation fails

### ISSUE THREAD

**Issue by akshaygd** [dnschneid/crouton#3117]
```
Please paste the output of the following command here: sudo edit-chroot -all
```eBizImac:~ cts$ npm install -g appium@1.6.3
/usr/local/bin/appium -> /usr/local/lib/node_modules/appium/build/lib/main.js

> sqlite3@3.1.8 install /usr/local/lib/node_modules/appium/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/usr/local/lib/node_modules/appium/node_modules/sqlite3/lib/binding/node-v51-darwin-x64/node_sqlite3.node" is installed via remote

> appium-chromedriver@2.9.4 install /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver
> node install-npm.js

info Chromedriver Install Installing Chromedriver version '2.25' for platform 'mac' and architecture '64'
info Chromedriver Install Opening temp file to write chromedriver_mac64 to...
info Chromedriver Install Downloading https://chromedriver.storage.googleapis.com/2.25/chromedriver_mac64.zip...
RequestError: Error: connect ETIMEDOUT 172.217.26.176:443
    at new RequestError (/usr/local/lib/node_modules/appium/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/appium/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/usr/local/lib/node_modules/appium/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:189:7)
    at Request.onRequestError (/usr/local/lib/node_modules/appium/node_modules/request/request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:189:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:189:7)
    at emitErrorNT (net.js:1280:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
/usr/local/lib
└── (empty)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/7.6.0/bin/node" "/usr/local/bin/npm" "install" "-g" "appium@1.6.3"
npm ERR! node v7.6.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! appium-chromedriver@2.9.4 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-chromedriver@2.9.4 install script 'node install-npm.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install-npm.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cts/.npm/_logs/2017-02-28T12_09_42_878Z-debug.log​

#### Please describe your issue:

Appium installation fails due to timeout on a URL for chromedriver. Exact error message pasted above. 
MAc OS: 10.11
npm version : 4.2.0
#### If known, describe the steps to reproduce the issue:

Run command npm install -g appium@1.6.3  from terminal of mac

**Comment by dnschneid** [comment]
#262
