### ISSUE TITLE
distro-release-upgrade hangs after installing bionic

### ISSUE THREAD

**Issue by biscuitlad** [dnschneid/crouton#4021]
Installed bionic, no errors. Ran 

sudo apt-get install update-manager-core python-apt

sudo do-release-upgrade

and the scripts started to upgrade. But it gets so far and then it just hangs installing system.conf
No error messages or anything, it just stops.

Unpacking libexpat1:amd64 (2.2.6-1) over (2.2.5-3) ...
Setting up libapparmor1:amd64 (2.12-4ubuntu8) ...
Setting up systemd (239-7ubuntu10.10) ...
Installing new version of config file /etc/systemd/journald.conf ...
Installing new version of config file /etc/systemd/logind.conf ...
Installing new version of config file /etc/systemd/resolved.conf ...
Installing new version of config file /etc/systemd/system.conf ...

After a while, Control-C kills the process at which point it claims:
No pending crash reports. Try --help for more information.

                                                          Could not install the upgrades 

                                                                                         The upgrade has aborted. Your system could be in an unusable state. A 
 recovery will run now (dpkg --configure -a). 

                                              dpkg: error: dpkg status database is locked by another process

                                                                                                            Upgrade complete 

                                                                                                                             The upgrade has completed but there were errors during the upgrade 
                                  process. 

                                           To continue please press [ENTER]

KeyboardInterrupt

                 The above exception was the direct cause of the following exception:

                                                                                     Traceback (most recent call last):
                                                                                                                         File "/tmp/ubuntu-release-upgrader-sy2etdtz/cosmic", line 8, in <module>
                                       sys.exit(main())
                                                         File "/tmp/ubuntu-release-upgrader-sy2etdtz/DistUpgrade/DistUpgradeMain.py", line 238, in main
                                                                                                                                                           if app.run():
            File "/tmp/ubuntu-release-upgrader-sy2etdtz/DistUpgrade/DistUpgradeController.py", line 2074, in run
                                                                                                                    return self.fullUpgrade()
                                                                                                                                               File "/tmp/ubuntu-release-upgrader-sy2etdtz/DistUpgrade/DistUpgradeController.py", line 2044, in fullUpgrade
                                                                                                 _("The upgrade has completed but there "File "/tmp/ubuntu-release-upgrader-sy2etdtz/DistUpgrade/DistUpgradeViewText.py", line 179, in information
                                                                                          readline()
                                                                                                      File "/tmp/ubuntu-release-upgrader-sy2etdtz/DistUpgrade/DistUpgradeViewText.py", line 51, in readline
                                                 s = input()
                                                            SystemError: <class 'UnicodeDecodeError'> returned a result with an error set
                                                                                                                                         Error in sys.excepthook:
   Traceback (most recent call last):
                                       File "/usr/lib/python3/dist-packages/problem_report.py", line 497, in add_to_existing
                                                                                                                                self.write(f)
                                                                                                                                               File "/usr/lib/python3/dist-packages/problem_report.py", line 450, in write
                                                                block = f.read(1048576)
                                                                                         File "/usr/lib/python3.6/codecs.py", line 321, in decode
                                                                                                                                                     (result, consumed) = self._buffer_decode(data, self.errors, final)
                                                         UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

                                                                                                                                                   Original exception was:
            KeyboardInterrupt

                             The above exception was the direct cause of the following exception:

                                                                                                 Traceback (most recent call last):
                                                                                                                                     File "/tmp/ubuntu-release-upgrader-sy2etdtz/cosmic", line 8, in <module>
                                                   sys.exit(main())
                                                                     File "/tmp/ubuntu-release-upgrader-sy2etdtz/DistUpgrade/DistUpgradeMain.py", line 238, in main
         if app.run():
File "/tmp/ubuntu-release-upgrader-sy2etdtz/DistUpgrade/DistUpgradeController.py", line 2074, in run
                                                                                                                                return self.fullUpgrade()
                                                                                                                                                           File "/tmp/ubuntu-release-upgrader-sy2etdtz/DistUpgrade/DistUpgradeController.py", line 2044, in fullUpgrade
                                                                                                             _("The upgrade has completed but there "
                                                                                                                                                       File "/tmp/ubuntu-release-upgrader-sy2etdtz/DistUpgrade/DistUpgradeViewText.py", line 179, in information
                                                                                                      readline()
                                                                                                                  File "/tmp/ubuntu-release-upgrader-sy2etdtz/DistUpgrade/DistUpgradeViewText.py", line 51, in readline
                                                             s = input()
                                                                        SystemError: <class 'UnicodeDecodeError'> returned a result with an error set

It ends with chroot being unusable (can't enter).

**Comment by biscuitlad** [comment]
Ran with graphical installer and it eventually got past that stage. Maybe didn't give it long enough (ten mins?!)
